services:
  - type: web
    name: agent-system-2
    env: node
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: COMMISSION_RATE
        value: 0.10
      - key: CLEAR_WINDOW_DAYS
        value: 14
      - key: COOKIE_TTL_DAYS
        value: 30
